# Initializations
POSTGRESQL_URI = "YOUR_POSTGRESQL_URI"
POSTGRESQL_USERNAME = "YOUR_POSTGRESQL_USERNAME"
POSTGRESQL_PASSWORD = "YOUR_POSTGRESQL_PASSWORD"
POSTGRESQL_DATABASE = "YOUR_POSTGRESQL_DATABASE"
